# action.yml
name: 'Sauce Connect Proxy Action'
description: 'A GitHub action to launch Sauce Connect Proxy'
author: Christian Bromann
branding:
    icon: server
    color: red
inputs:
    apiAddress:
        description: 'host:port for the status server used to expose client status.'
        required: false
    accessKey:
        description: Sauce Labs API Key.
        required: true
    cacertFile:
        description: CA certificate bundle to use for verifying REST connections. (default "/usr/local/etc/openssl/cert.pem")
        required: false
    configFile:
        description: Path to YAML config file. Please refer to https://docs.saucelabs.com/secure-connections/sauce-connect/setup-configuration/yaml-config/.
        required: false
    directDomains:
        description: Comma-separated list of domains that you want to relay directly through the internet instead of through the Sauce Connect Proxy tunnel.
        required: false
    dnsServer:
        description: 'Use specified name server. To specify multiple servers, separate them with comma. Use IP addresses, optionally with a port number, the two separated by a colon. Example: --dns 8.8.8.8,8.8.4.4:53'
        required: false
    denyDomains:
        description: Comma-separated list of regular expressions. Requests matching one of these will get dropped instantly and will not go through the tunnel.
        required: false
    logLevel:
        description: Specify log level.
        required: false
    logHttp:
        description: HTTP request and response logging mode.
        required: false
    metricsAddress:
        description: '[DEPRECATED in 4.8.0] host:port for the status server used to expose client metrics.'
        required: false
    pac:
        description: Proxy autoconfiguration. Can be an http(s) or local file:// (absolute path only) URI.
        required: false
    proxy:
        description: Proxy host and port that Sauce Connect should use to connect to the Sauce Labs cloud.
        required: false
    proxyLocalhost:
        description: Configure localhost access; allow, direct, deny
        required: false
    proxySauce:
        description: Use the proxy configured with -p for the tunnel connection.
        required: false
    proxyUserpwd:
        description: Username and password required to access the proxy configured with -p.
        required: false
    region:
        description: Sets your Sauce Labs region data center such as us-west, eu-central, etc... For more information, please refer to https://docs.saucelabs.com/basics/data-center-endpoints/ or https://github.com/saucelabs/node-saucelabs?tab=readme-ov-file#region.
        required: true
    restUrl:
        description: Sets your Sauce Labs regional data center REST API URL (e.g., EU-Central, US-West). We recommend to use `region` instead.
        required: false
    scproxyPort:
        description: Port on which scproxy will be listening.
        required: false
    scVersion:
        description: Version of the saucelabs/sauce-connect docker image.
        required: false
        default: '5'
    sePort:
        description: Port on which Sauce Connect's Selenium relay will listen for requests. Selenium commands reaching Connect on this port will be relayed to Sauce Labs securely and reliably through Connect's tunnel (default 4445)
        required: false
    shared:
        description: Share the tunnels within the same organization.
        required: false
    tlsPassthroughDomains:
        description: Comma-separated list of domains. Requests whose host matches one of these will not be SSL re-encrypted.
        required: false
    tunnelDomains:
        description: Inverse of '--direct-domains'. Only requests for domains in this list will be sent through the tunnel. Overrides '--direct-domains'.
        required: false
    tunnelIdentifier:
        description: Assigns a name to a Sauce Connect Proxy tunnel. Use tunnelName starting from Sauce Connect v4.7.0.
        required: false
    tunnelName:
        description: Assigns a name to a Sauce Connect Proxy tunnel. Same as tunnelIdentifier.
        required: true
    tunnelPool:
        description: Launches a high availability tunnel pool along with the --tunnel-identifier flag. For more info, please refer to https://docs.saucelabs.com/secure-connections/sauce-connect/setup-configuration/high-availability/.
        required: false
    username:
        description: Sauce Labs user name.
        required: true
    retryTimeout:
        description: Do not retry if this amount of minutes has passed since starting.
        required: false
        default: '5'
runs:
    using: 'node20'
    main: 'dist/main/index.js'
    post: 'dist/post/index.js'
